// Generated on Fri Aug 14 21:16:45 +0200 2009 from /home/elven/code/nwnx2-linux/trunk/plugins/ice/build/funcs.nss

#include "FunctionHooks.h"
#include "NWNStructures.h"
#include "NWScript.h"
#include <iostream>

class NWScriptI : public NWN::NWScript {
  public:
    NWScriptI();
    void lock(const char*);
    void unlock(const char*);
    void resetPerEventMappings();
    unsigned long callCounter;
    bool lockingEnabled;
    bool inContext;
    bool hasState(const std::string&, const Ice::Current&);
    NWN::Persistable getState(const std::string&, const Ice::Current&);
    void putState(const std::string&, const NWN::Persistable&, const Ice::Current&);
    void delState(const std::string&, const Ice::Current&);
    void clearState(const Ice::Current&);

    NWN::NWObjectSeq allPCs(const Ice::Current&);
    NWN::NWEffectSeq allEffects(const NWN::NWObject&, const Ice::Current&);
    NWN::NWObjectSeq allInArea(const NWN::NWObject&, const Ice::Current&);
    NWN::NWObjectSeq allInInventory(const NWN::NWObject&, const Ice::Current&);
    NWN::NWCreatureEquipped allEquipped(const NWN::NWObject&, const Ice::Current&);
    NWN::NWItemPropertySeq allItemProperties(const NWN::NWObject&, const Ice::Current&);
    NWN::NWObjectSeq allInShape(NWN::ShapeType shape, Ice::Double size,
      const NWN::NWLocation& location, bool lineOfSight, NWN::ObjectType objType,
      const NWN::NWVector& origin, const Ice::Current&);
    NWN::NWObjectSeq allInFaction(const NWN::NWObject&, bool, const Ice::Current&);

    bool getEffectIconShown(const NWN::NWEffect&, const Ice::Current&);
    void setEffectIconShown(const NWN::NWEffect&, bool, const Ice::Current&);
    virtual Ice::Int abs(Ice::Int nValue, const Ice::Current&);
    virtual Ice::Double acos(Ice::Double fValue, const Ice::Current&);
    virtual void actionAttack(const NWN::NWObject& oAttackee, bool bPassive, const Ice::Current&);
    virtual void actionCastFakeSpellAtLocation(Ice::Int nSpell, const NWN::NWLocation& lTarget, NWN::ProjectilePathType tProjectilePathType, const Ice::Current&);
    virtual void actionCastFakeSpellAtObject(Ice::Int nSpell, const NWN::NWObject& oTarget, NWN::ProjectilePathType tProjectilePathType, const Ice::Current&);
    virtual void actionCastSpellAtLocation(Ice::Int nSpell, const NWN::NWLocation& lTargetLocation, NWN::MetaMagic tMetaMagic, bool bCheat, NWN::ProjectilePathType tProjectilePathType, bool bInstantSpell, const Ice::Current&);
    virtual void actionCastSpellAtObject(Ice::Int nSpell, const NWN::NWObject& oTarget, NWN::MetaMagic tMetaMagic, bool bCheat, Ice::Int nDomainLevel, NWN::ProjectilePathType tProjectilePathType, bool bInstantSpell, const Ice::Current&);
    virtual void actionCloseDoor(const NWN::NWObject& oDoor, const Ice::Current&);
    virtual void actionCounterSpell(const NWN::NWObject& oCounterSpellTarget, const Ice::Current&);
    virtual void actionEquipItem(const NWN::NWObject& oItem, NWN::InventorySlot tInventorySlot, const Ice::Current&);
    virtual void actionEquipMostDamagingMelee(const NWN::NWObject& oVersus, bool bOffHand, const Ice::Current&);
    virtual void actionEquipMostDamagingRanged(const NWN::NWObject& oVersus, const Ice::Current&);
    virtual void actionEquipMostEffectiveArmor(const Ice::Current&);
    virtual void actionExamine(const NWN::NWObject& oExamine, const Ice::Current&);
    virtual void actionForceFollowObject(const NWN::NWObject& oFollow, Ice::Double fFollowDistance, const Ice::Current&);
    virtual void actionForceMoveToLocation(const NWN::NWLocation& lDestination, bool bRun, Ice::Double fTimeout, const Ice::Current&);
    virtual void actionForceMoveToObject(const NWN::NWObject& oMoveTo, bool bRun, Ice::Double fRange, Ice::Double fTimeout, const Ice::Current&);
    virtual void actionGiveItem(const NWN::NWObject& oItem, const NWN::NWObject& oGiveTo, const Ice::Current&);
    virtual void actionInteractObject(const NWN::NWObject& oPlaceable, const Ice::Current&);
    virtual void actionJumpToLocation(const NWN::NWLocation& lLocation, const Ice::Current&);
    virtual void actionJumpToObject(const NWN::NWObject& oToJumpTo, bool bWalkStraightLineToPoint, const Ice::Current&);
    virtual void actionLockObject(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void actionMoveAwayFromLocation(const NWN::NWLocation& lMoveAwayFrom, bool bRun, Ice::Double fMoveAwayRange, const Ice::Current&);
    virtual void actionMoveAwayFromObject(const NWN::NWObject& oFleeFrom, bool bRun, Ice::Double fMoveAwayRange, const Ice::Current&);
    virtual void actionMoveToLocation(const NWN::NWLocation& lDestination, bool bRun, const Ice::Current&);
    virtual void actionMoveToObject(const NWN::NWObject& oMoveTo, bool bRun, Ice::Double fRange, const Ice::Current&);
    virtual void actionOpenDoor(const NWN::NWObject& oDoor, const Ice::Current&);
    virtual void actionPauseConversation(const Ice::Current&);
    virtual void actionPickUpItem(const NWN::NWObject& oItem, const Ice::Current&);
    virtual void actionPlayAnimation(Ice::Int nAnimation, Ice::Double fSpeed, Ice::Double fDurationSeconds, const Ice::Current&);
    virtual void actionPutDownItem(const NWN::NWObject& oItem, const Ice::Current&);
    virtual void actionRandomWalk(const Ice::Current&);
    virtual void actionRest(bool bCreatureToEnemyLineOfSightCheck, const Ice::Current&);
    virtual void actionResumeConversation(const Ice::Current&);
    virtual void actionSit(const NWN::NWObject& oChair, const Ice::Current&);
    virtual void actionSpeakString(const std::string& sStringToSpeak, NWN::TalkVolume tTalkVolume, const Ice::Current&);
    virtual void actionSpeakStringByStrRef(Ice::Int nStrRef, NWN::TalkVolume tTalkVolume, const Ice::Current&);
    virtual void actionStartConversation(const NWN::NWObject& oObjectToConverseWith, const std::string& sDialogResRef, bool bPrivateConversation, bool bPlayHello, const Ice::Current&);
    virtual void actionTakeItem(const NWN::NWObject& oItem, const NWN::NWObject& oTakeFrom, const Ice::Current&);
    virtual void actionUnequipItem(const NWN::NWObject& oItem, const Ice::Current&);
    virtual void actionUnlockObject(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void actionUseFeat(Ice::Int nFeat, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void actionUseSkill(Ice::Int nSkill, const NWN::NWObject& oTarget, Ice::Int nSubSkill, const NWN::NWObject& oItemUsed, const Ice::Current&);
    virtual void actionWait(Ice::Double fSeconds, const Ice::Current&);
    virtual void activatePortal(const NWN::NWObject& oTarget, const std::string& sIPaddress, const std::string& sPassword, const std::string& sWaypointTag, bool bSeemless, const Ice::Current&);
    virtual void addHenchman(const NWN::NWObject& oMaster, const NWN::NWObject& oHenchman, const Ice::Current&);
    virtual void addItemProperty(NWN::DurationType tDurationType, const NWN::NWItemProperty& ipProperty, const NWN::NWObject& oItem, Ice::Double fDuration, const Ice::Current&);
    virtual void addJournalQuestEntry(const std::string& szPlotID, Ice::Int nState, const NWN::NWObject& oCreature, bool bAllPartyMembers, bool bAllPlayers, bool bAllowOverrideHigher, const Ice::Current&);
    virtual void addToParty(const NWN::NWObject& oPC, const NWN::NWObject& oPartyLeader, const Ice::Current&);
    virtual void adjustAlignment(const NWN::NWObject& oSubject, Ice::Int nAlignment, Ice::Int nShift, bool bAllPartyMembers, const Ice::Current&);
    virtual void adjustReputation(const NWN::NWObject& oTarget, const NWN::NWObject& oSourceFactionMember, Ice::Int nAdjustment, const Ice::Current&);
    virtual void ambientSoundChangeDay(const NWN::NWObject& oArea, Ice::Int nTrack, const Ice::Current&);
    virtual void ambientSoundChangeNight(const NWN::NWObject& oArea, Ice::Int nTrack, const Ice::Current&);
    virtual void ambientSoundPlay(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void ambientSoundSetDayVolume(const NWN::NWObject& oArea, Ice::Int nVolume, const Ice::Current&);
    virtual void ambientSoundSetNightVolume(const NWN::NWObject& oArea, Ice::Int nVolume, const Ice::Current&);
    virtual void ambientSoundStop(const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::NWVector angleToVector(Ice::Double fAngle, const Ice::Current&);
    virtual void applyEffectAtLocation(NWN::DurationType tDurationType, const NWN::NWEffect& eEffect, const NWN::NWLocation& lLocation, Ice::Double fDuration, const Ice::Current&);
    virtual void applyEffectToObject(NWN::DurationType tDurationType, const NWN::NWEffect& eEffect, const NWN::NWObject& oTarget, Ice::Double fDuration, const Ice::Current&);
    virtual Ice::Double asin(Ice::Double fValue, const Ice::Current&);
    virtual Ice::Double atan(Ice::Double fValue, const Ice::Current&);
    virtual NWN::NWItemProperty badBadReplaceMeThisDoesNothing(const Ice::Current&);
    virtual Ice::Int beginConversation(const std::string& sResRef, const NWN::NWObject& oObjectToDialog, const Ice::Current&);
    virtual void blackScreen(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void bootPC(const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void changeFaction(const NWN::NWObject& oObjectToChangeFaction, const NWN::NWObject& oMemberOfFactionToJoin, const Ice::Current&);
    virtual void changeToStandardFaction(const NWN::NWObject& oCreatureToChange, NWN::StandardFaction tStandardFaction, const Ice::Current&);
    virtual void clearAllActions(bool bClearCombatState, const Ice::Current&);
    virtual void clearPersonalReputation(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual NWN::NWObject copyItem(const NWN::NWObject& oItem, const NWN::NWObject& oTargetInventory, bool bCopyVars, const Ice::Current&);
    virtual NWN::NWObject copyItemAndModify(const NWN::NWObject& oItem, Ice::Int nType, Ice::Int nIndex, Ice::Int nNewValue, bool bCopyVars, const Ice::Current&);
    virtual NWN::NWObject copyObject(const NWN::NWObject& oSource, const NWN::NWLocation& locLocation, const NWN::NWObject& oOwner, const std::string& sNewTag, const Ice::Current&);
    virtual Ice::Double cos(Ice::Double fValue, const Ice::Current&);
    virtual NWN::NWObject createItemOnObject(const std::string& sItemTemplate, const NWN::NWObject& oTarget, Ice::Int nStackSize, const std::string& sNewTag, const Ice::Current&);
    virtual NWN::NWObject createObject(NWN::ObjectType tObjectType, const std::string& sTemplate, const NWN::NWLocation& lLocation, bool bUseAppearAnimation, const std::string& sNewTag, const Ice::Current&);
    virtual NWN::NWObject createTrapAtLocation(Ice::Int nTrapType, const NWN::NWLocation& lLocation, Ice::Double fSize, const std::string& sTag, NWN::StandardFaction tStandardFaction, const std::string& sOnDisarmScript, const std::string& sOnTrapTriggeredScript, const Ice::Current&);
    virtual void createTrapOnObject(Ice::Int nTrapType, const NWN::NWObject& oObject, NWN::StandardFaction tStandardFaction, const std::string& sOnDisarmScript, const std::string& sOnTrapTriggeredScript, const Ice::Current&);
    virtual Ice::Int d10(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d100(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d12(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d2(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d20(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d3(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d4(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d6(Ice::Int nNumDice, const Ice::Current&);
    virtual Ice::Int d8(Ice::Int nNumDice, const Ice::Current&);
    virtual void dayToNight(const NWN::NWObject& oPlayer, Ice::Double fTransitionTime, const Ice::Current&);
    virtual void decrementRemainingFeatUses(const NWN::NWObject& oCreature, Ice::Int nFeat, const Ice::Current&);
    virtual void decrementRemainingSpellUses(const NWN::NWObject& oCreature, Ice::Int nSpell, const Ice::Current&);
    virtual void deleteCampaignVariable(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void deleteLocalFloat(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual void deleteLocalInt(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual void deleteLocalLocation(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual void deleteLocalObject(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual void deleteLocalString(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual void destroyCampaignDatabase(const std::string& sCampaignName, const Ice::Current&);
    virtual void destroyObject(const NWN::NWObject& oDestroy, Ice::Double fDelay, const Ice::Current&);
    virtual void doDoorAction(const NWN::NWObject& oTargetDoor, NWN::DoorAction tDoorAction, const Ice::Current&);
    virtual void doPlaceableObjectAction(const NWN::NWObject& oPlaceable, NWN::PlaceableAction tPlaceableAction, const Ice::Current&);
    virtual void doSinglePlayerAutoSave(const Ice::Current&);
    virtual void doWhirlwindAttack(bool bDisplayFeedback, bool bImproved, const Ice::Current&);
    virtual NWN::NWEffect effectACDecrease(Ice::Int nValue, Ice::Int nModifyType, Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWEffect effectACIncrease(Ice::Int nValue, Ice::Int nModifyType, Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWEffect effectAbilityDecrease(NWN::Ability tAbility, Ice::Int nModifyBy, const Ice::Current&);
    virtual NWN::NWEffect effectAbilityIncrease(NWN::Ability tAbility, Ice::Int nModifyBy, const Ice::Current&);
    virtual NWN::NWEffect effectAppear(Ice::Int nAnimation, const Ice::Current&);
    virtual NWN::NWEffect effectAreaOfEffect(Ice::Int nAreaEffectId, const std::string& sOnEnterScript, const std::string& sHeartbeatScript, const std::string& sOnExitScript, const Ice::Current&);
    virtual NWN::NWEffect effectAttackDecrease(Ice::Int nPenalty, Ice::Int nModifierType, const Ice::Current&);
    virtual NWN::NWEffect effectAttackIncrease(Ice::Int nBonus, Ice::Int nModifierType, const Ice::Current&);
    virtual NWN::NWEffect effectBeam(Ice::Int nBeamVisualEffect, const NWN::NWObject& oEffector, Ice::Int nBodyPart, bool bMissEffect, const Ice::Current&);
    virtual NWN::NWEffect effectBlindness(const Ice::Current&);
    virtual NWN::NWEffect effectCharmed(const Ice::Current&);
    virtual NWN::NWEffect effectConcealment(Ice::Int nPercentage, Ice::Int nMissType, const Ice::Current&);
    virtual NWN::NWEffect effectConfused(const Ice::Current&);
    virtual NWN::NWEffect effectCurse(Ice::Int nStrMod, Ice::Int nDexMod, Ice::Int nConMod, Ice::Int nIntMod, Ice::Int nWisMod, Ice::Int nChaMod, const Ice::Current&);
    virtual NWN::NWEffect effectCutsceneDominated(const Ice::Current&);
    virtual NWN::NWEffect effectCutsceneGhost(const Ice::Current&);
    virtual NWN::NWEffect effectCutsceneImmobilize(const Ice::Current&);
    virtual NWN::NWEffect effectCutsceneParalyze(const Ice::Current&);
    virtual NWN::NWEffect effectDamage(Ice::Int nDamageAmount, Ice::Int nDamageType, Ice::Int nDamagePower, const Ice::Current&);
    virtual NWN::NWEffect effectDamageDecrease(Ice::Int nPenalty, Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWEffect effectDamageImmunityDecrease(Ice::Int nDamageType, Ice::Int nPercentImmunity, const Ice::Current&);
    virtual NWN::NWEffect effectDamageImmunityIncrease(Ice::Int nDamageType, Ice::Int nPercentImmunity, const Ice::Current&);
    virtual NWN::NWEffect effectDamageIncrease(Ice::Int nBonus, Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWEffect effectDamageReduction(Ice::Int nAmount, Ice::Int nDamagePower, Ice::Int nLimit, const Ice::Current&);
    virtual NWN::NWEffect effectDamageResistance(Ice::Int nDamageType, Ice::Int nAmount, Ice::Int nLimit, const Ice::Current&);
    virtual NWN::NWEffect effectDamageShield(Ice::Int nDamageAmount, Ice::Int nRandomAmount, Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWEffect effectDarkness(const Ice::Current&);
    virtual NWN::NWEffect effectDazed(const Ice::Current&);
    virtual NWN::NWEffect effectDeaf(const Ice::Current&);
    virtual NWN::NWEffect effectDeath(bool bSpectacularDeath, bool bDisplayFeedback, const Ice::Current&);
    virtual NWN::NWEffect effectDisappear(Ice::Int nAnimation, const Ice::Current&);
    virtual NWN::NWEffect effectDisappearAppear(const NWN::NWLocation& lLocation, Ice::Int nAnimation, const Ice::Current&);
    virtual NWN::NWEffect effectDisease(Ice::Int nDiseaseType, const Ice::Current&);
    virtual NWN::NWEffect effectDispelMagicAll(Ice::Int nCasterLevel, const Ice::Current&);
    virtual NWN::NWEffect effectDispelMagicBest(Ice::Int nCasterLevel, const Ice::Current&);
    virtual NWN::NWEffect effectDominated(const Ice::Current&);
    virtual NWN::NWEffect effectEntangle(const Ice::Current&);
    virtual NWN::NWEffect effectEthereal(const Ice::Current&);
    virtual NWN::NWEffect effectFrightened(const Ice::Current&);
    virtual NWN::NWEffect effectHaste(const Ice::Current&);
    virtual NWN::NWEffect effectHeal(Ice::Int nDamageToHeal, const Ice::Current&);
    virtual NWN::NWEffect effectHitPointChangeWhenDying(Ice::Double fHitPointChangePerRound, const Ice::Current&);
    virtual NWN::NWEffect effectImmunity(Ice::Int nImmunityType, const Ice::Current&);
    virtual NWN::NWEffect effectInvisibility(Ice::Int nInvisibilityType, const Ice::Current&);
    virtual NWN::NWEffect effectKnockdown(const Ice::Current&);
    virtual NWN::NWEffect effectLinkEffects(const NWN::NWEffect& eChildEffect, const NWN::NWEffect& eParentEffect, const Ice::Current&);
    virtual NWN::NWEffect effectMissChance(Ice::Int nPercentage, Ice::Int nMissChanceType, const Ice::Current&);
    virtual NWN::NWEffect effectModifyAttacks(Ice::Int nAttacks, const Ice::Current&);
    virtual NWN::NWEffect effectMovementSpeedDecrease(Ice::Int nPercentChange, const Ice::Current&);
    virtual NWN::NWEffect effectMovementSpeedIncrease(Ice::Int nPercentChange, const Ice::Current&);
    virtual NWN::NWEffect effectNegativeLevel(Ice::Int nNumLevels, bool bHPBonus, const Ice::Current&);
    virtual NWN::NWEffect effectParalyze(const Ice::Current&);
    virtual NWN::NWEffect effectPetrify(const Ice::Current&);
    virtual NWN::NWEffect effectPoison(Ice::Int nPoisonType, const Ice::Current&);
    virtual NWN::NWEffect effectPolymorph(Ice::Int nPolymorphSelection, bool bLocked, const Ice::Current&);
    virtual NWN::NWEffect effectRegenerate(Ice::Int nAmount, Ice::Double fIntervalSeconds, const Ice::Current&);
    virtual NWN::NWEffect effectResurrection(const Ice::Current&);
    virtual NWN::NWEffect effectSanctuary(Ice::Int nDifficultyClass, const Ice::Current&);
    virtual NWN::NWEffect effectSavingThrowDecrease(Ice::Int nSave, Ice::Int nValue, NWN::SaveType tSaveType, const Ice::Current&);
    virtual NWN::NWEffect effectSavingThrowIncrease(Ice::Int nSave, Ice::Int nValue, NWN::SaveType tSaveType, const Ice::Current&);
    virtual NWN::NWEffect effectSeeInvisible(const Ice::Current&);
    virtual NWN::NWEffect effectSilence(const Ice::Current&);
    virtual NWN::NWEffect effectSkillDecrease(Ice::Int nSkill, Ice::Int nValue, const Ice::Current&);
    virtual NWN::NWEffect effectSkillIncrease(Ice::Int nSkill, Ice::Int nValue, const Ice::Current&);
    virtual NWN::NWEffect effectSleep(const Ice::Current&);
    virtual NWN::NWEffect effectSlow(const Ice::Current&);
    virtual NWN::NWEffect effectSpellFailure(Ice::Int nPercent, NWN::SpellSchool tSpellSchool, const Ice::Current&);
    virtual NWN::NWEffect effectSpellImmunity(Ice::Int nImmunityToSpell, const Ice::Current&);
    virtual NWN::NWEffect effectSpellLevelAbsorption(Ice::Int nMaxSpellLevelAbsorbed, Ice::Int nTotalSpellLevelsAbsorbed, NWN::SpellSchool tSpellSchool, const Ice::Current&);
    virtual NWN::NWEffect effectSpellResistanceDecrease(Ice::Int nValue, const Ice::Current&);
    virtual NWN::NWEffect effectSpellResistanceIncrease(Ice::Int nValue, const Ice::Current&);
    virtual NWN::NWEffect effectStunned(const Ice::Current&);
    virtual NWN::NWEffect effectSummonCreature(const std::string& sCreatureResref, Ice::Int nVisualEffectId, Ice::Double fDelaySeconds, bool bUseAppearAnimation, const Ice::Current&);
    virtual NWN::NWEffect effectSwarm(Ice::Int nLooping, const std::string& sCreatureTemplate1, const std::string& sCreatureTemplate2, const std::string& sCreatureTemplate3, const std::string& sCreatureTemplate4, const Ice::Current&);
    virtual NWN::NWEffect effectTemporaryHitpoints(Ice::Int nHitPoints, const Ice::Current&);
    virtual NWN::NWEffect effectTimeStop(const Ice::Current&);
    virtual NWN::NWEffect effectTrueSeeing(const Ice::Current&);
    virtual NWN::NWEffect effectTurnResistanceDecrease(Ice::Int nHitDice, const Ice::Current&);
    virtual NWN::NWEffect effectTurnResistanceIncrease(Ice::Int nHitDice, const Ice::Current&);
    virtual NWN::NWEffect effectTurned(const Ice::Current&);
    virtual NWN::NWEffect effectUltravision(const Ice::Current&);
    virtual NWN::NWEffect effectVisualEffect(Ice::Int nVisualEffectId, bool bMissEffect, const Ice::Current&);
    virtual void endGame(const std::string& sEndMovie, const Ice::Current&);
    virtual void executeScript(const std::string& sScript, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void exploreAreaForPlayer(const NWN::NWObject& oArea, const NWN::NWObject& oPlayer, bool bExplored, const Ice::Current&);
    virtual void exportAllCharacters(const Ice::Current&);
    virtual void exportSingleCharacter(const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual NWN::NWEffect extraordinaryEffect(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual Ice::Double fabs(Ice::Double fValue, const Ice::Current&);
    virtual void fadeFromBlack(const NWN::NWObject& oCreature, Ice::Double fSpeed, const Ice::Current&);
    virtual void fadeToBlack(const NWN::NWObject& oCreature, Ice::Double fSpeed, const Ice::Current&);
    virtual Ice::Double feetToMeters(Ice::Double fFeet, const Ice::Current&);
    virtual Ice::Int findSubString(const std::string& sString, const std::string& sSubString, Ice::Int nStart, const Ice::Current&);
    virtual Ice::Int floatToInt(Ice::Double fFloat, const Ice::Current&);
    virtual std::string floatToString(Ice::Double fFloat, Ice::Int nWidth, Ice::Int nDecimals, const Ice::Current&);
    virtual void floatingTextStrRefOnCreature(Ice::Int nStrRefToDisplay, const NWN::NWObject& oCreatureToFloatAbove, bool bBroadcastToFaction, const Ice::Current&);
    virtual void floatingTextStringOnCreature(const std::string& sStringToDisplay, const NWN::NWObject& oCreatureToFloatAbove, bool bBroadcastToFaction, const Ice::Current&);
    virtual void forceRest(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::SavingThrowResult fortitudeSave(const NWN::NWObject& oCreature, Ice::Int nDC, NWN::SaveType tSaveType, const NWN::NWObject& oSaveVersus, const Ice::Current&);
    virtual std::string get2DAString(const std::string& s2DA, const std::string& sColumn, Ice::Int nRow, const Ice::Current&);
    virtual Ice::Int getAC(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Int getAILevel(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getAbilityModifier(NWN::Ability tAbility, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getAbilityScore(const NWN::NWObject& oCreature, NWN::Ability tAbility, bool bBaseAbilityScore, const Ice::Current&);
    virtual bool getActionMode(const NWN::NWObject& oCreature, NWN::ActionMode tActionMode, const Ice::Current&);
    virtual Ice::Int getAge(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getAlignmentGoodEvil(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getAlignmentLawChaos(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getAnimalCompanionCreatureType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual std::string getAnimalCompanionName(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getAppearanceType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getArcaneSpellFailure(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getArea(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWObject getAreaFromLocation(const NWN::NWLocation& lLocation, const Ice::Current&);
    virtual NWN::NWObject getAreaOfEffectCreator(const NWN::NWObject& oAreaOfEffectObject, const Ice::Current&);
    virtual Ice::Int getAreaSize(Ice::Int nAreaDimension, const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::NWObject getAssociate(NWN::AssociateType tAssociateType, const NWN::NWObject& oMaster, Ice::Int nTh, const Ice::Current&);
    virtual NWN::AssociateType getAssociateType(const NWN::NWObject& oAssociate, const Ice::Current&);
    virtual NWN::NWObject getAttackTarget(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getAttemptedAttackTarget(const Ice::Current&);
    virtual NWN::NWObject getAttemptedSpellTarget(const Ice::Current&);
    virtual Ice::Int getBaseAttackBonus(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getBaseItemType(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getBlockingDoor(const Ice::Current&);
    virtual Ice::Int getCalendarDay(const Ice::Current&);
    virtual Ice::Int getCalendarMonth(const Ice::Current&);
    virtual Ice::Int getCalendarYear(const Ice::Current&);
    virtual Ice::Double getCampaignFloat(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual Ice::Int getCampaignInt(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual NWN::NWLocation getCampaignLocation(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual std::string getCampaignString(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual NWN::NWVector getCampaignVector(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual Ice::Int getCasterLevel(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Double getChallengeRating(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getClassByPosition(Ice::Int nClassPosition, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getClickingObject(const Ice::Current&);
    virtual Ice::Int getColor(const NWN::NWObject& oObject, Ice::Int nColorChannel, const Ice::Current&);
    virtual bool getCommandable(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getCreatureBodyPart(Ice::Int nPart, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::CreatureSize getCreatureSize(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getCreatureStartingPackage(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getCreatureTailType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getCreatureWingType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::Action getCurrentAction(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Int getCurrentHitPoints(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Double getCutsceneCameraMoveRate(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getCutsceneMode(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getDamageDealtByType(Ice::Int nDamageType, const Ice::Current&);
    virtual Ice::Int getDefensiveCastingMode(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual std::string getDeity(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual std::string getDescription(const NWN::NWObject& oObject, bool bOriginalDescription, bool bIdentifiedDescription, const Ice::Current&);
    virtual Ice::Int getDetectMode(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Double getDialogSoundLength(Ice::Int nStrRef, const Ice::Current&);
    virtual Ice::Double getDistanceBetween(const NWN::NWObject& oObjectA, const NWN::NWObject& oObjectB, const Ice::Current&);
    virtual Ice::Double getDistanceBetweenLocations(const NWN::NWLocation& lLocationA, const NWN::NWLocation& lLocationB, const Ice::Current&);
    virtual Ice::Double getDistanceToObject(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getDroppableFlag(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getEffectCreator(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual NWN::DurationType getEffectDurationType(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual Ice::Int getEffectSpellId(const NWN::NWEffect& eSpellEffect, const Ice::Current&);
    virtual NWN::EffectSubType getEffectSubType(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual NWN::EffectType getEffectType(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual Ice::Int getEncounterActive(const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual Ice::Int getEncounterDifficulty(const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual Ice::Int getEncounterSpawnsCurrent(const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual Ice::Int getEncounterSpawnsMax(const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual NWN::NWObject getEnteringObject(const Ice::Current&);
    virtual NWN::NWObject getExitingObject(const Ice::Current&);
    virtual Ice::Double getFacing(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Double getFacingFromLocation(const NWN::NWLocation& lLocation, const Ice::Current&);
    virtual Ice::Int getFactionAverageGoodEvilAlignment(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual Ice::Int getFactionAverageLawChaosAlignment(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual Ice::Int getFactionAverageLevel(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual Ice::Int getFactionAverageReputation(const NWN::NWObject& oSourceFactionMember, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getFactionAverageXP(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual NWN::NWObject getFactionBestAC(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual bool getFactionEqual(const NWN::NWObject& oFirstObject, const NWN::NWObject& oSecondObject, const Ice::Current&);
    virtual Ice::Int getFactionGold(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual NWN::NWObject getFactionLeader(const NWN::NWObject& oMemberOfFaction, const Ice::Current&);
    virtual NWN::NWObject getFactionLeastDamagedMember(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual NWN::NWObject getFactionMostDamagedMember(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual Ice::Int getFactionMostFrequentClass(const NWN::NWObject& oFactionMember, const Ice::Current&);
    virtual NWN::NWObject getFactionStrongestMember(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual NWN::NWObject getFactionWeakestMember(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual NWN::NWObject getFactionWorstAC(const NWN::NWObject& oFactionMember, bool bMustBeVisible, const Ice::Current&);
    virtual Ice::Int getFamiliarCreatureType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual std::string getFamiliarName(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWEffect getFirstEffect(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getFirstFactionMember(const NWN::NWObject& oMemberOfFaction, bool bPCOnly, const Ice::Current&);
    virtual NWN::NWObject getFirstInPersistentObject(const NWN::NWObject& oPersistentObject, Ice::Int nResidentObjectType, Ice::Int nPersistentZone, const Ice::Current&);
    virtual NWN::NWObject getFirstItemInInventory(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWItemProperty getFirstItemProperty(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getFirstObjectInArea(const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::NWObject getFirstObjectInShape(NWN::ShapeType tShapeType, Ice::Double fSize, const NWN::NWLocation& lTarget, bool bLineOfSight, Ice::Int nObjectFilter, const NWN::NWVector& vOrigin, const Ice::Current&);
    virtual NWN::NWObject getFirstPC(const Ice::Current&);
    virtual Ice::Int getFogAmount(Ice::Int nFogType, const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int getFogColor(Ice::Int nFogType, const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int getFootstepType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getFortitudeSavingThrow(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getGameDifficulty(const Ice::Current&);
    virtual NWN::Gender getGender(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getGoingToBeAttackedBy(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getGold(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getGoldPieceValue(const NWN::NWObject& oItem, const Ice::Current&);
    virtual Ice::Int getGoodEvilValue(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getHardness(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getHasFeat(Ice::Int nFeat, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getHasFeatEffect(Ice::Int nFeat, const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getHasInventory(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getHasSkill(Ice::Int nSkill, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getHasSpell(Ice::Int nSpell, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getHasSpellEffect(Ice::Int nSpell, const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::NWObject getHenchman(const NWN::NWObject& oMaster, Ice::Int nNth, const Ice::Current&);
    virtual Ice::Int getHitDice(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIdentified(const NWN::NWObject& oItem, const Ice::Current&);
    virtual bool getImmortal(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual bool getInfiniteFlag(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getInventoryDisturbItem(const Ice::Current&);
    virtual Ice::Int getInventoryDisturbType(const Ice::Current&);
    virtual bool getIsAreaAboveGround(const NWN::NWObject& oArea, const Ice::Current&);
    virtual bool getIsAreaInterior(const NWN::NWObject& oArea, const Ice::Current&);
    virtual bool getIsAreaNatural(const NWN::NWObject& oArea, const Ice::Current&);
    virtual bool getIsCreatureDisarmable(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsDM(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsDMPossessed(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsDawn(const Ice::Current&);
    virtual bool getIsDay(const Ice::Current&);
    virtual bool getIsDead(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsDoorActionPossible(const NWN::NWObject& oTargetDoor, NWN::DoorAction tDoorAction, const Ice::Current&);
    virtual bool getIsDusk(const Ice::Current&);
    virtual bool getIsEffectValid(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual bool getIsEncounterCreature(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsEnemy(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsFriend(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsImmune(const NWN::NWObject& oCreature, Ice::Int nImmunityType, const NWN::NWObject& oVersus, const Ice::Current&);
    virtual bool getIsInCombat(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsInSubArea(const NWN::NWObject& oCreature, const NWN::NWObject& oSubArea, const Ice::Current&);
    virtual bool getIsItemPropertyValid(const NWN::NWItemProperty& ipProperty, const Ice::Current&);
    virtual bool getIsListening(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getIsNeutral(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsNight(const Ice::Current&);
    virtual bool getIsObjectValid(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getIsOpen(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getIsPC(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsPlaceableObjectActionPossible(const NWN::NWObject& oPlaceable, NWN::PlaceableAction tPlaceableAction, const Ice::Current&);
    virtual bool getIsPlayableRacialType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsPossessedFamiliar(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsReactionTypeFriendly(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsReactionTypeHostile(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsReactionTypeNeutral(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getIsResting(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getIsSkillSuccessful(const NWN::NWObject& oTarget, Ice::Int nSkill, Ice::Int nDifficulty, const Ice::Current&);
    virtual bool getIsTrapped(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getIsWeaponEffective(const NWN::NWObject& oVersus, bool bOffHand, const Ice::Current&);
    virtual Ice::Int getItemACValue(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getItemActivated(const Ice::Current&);
    virtual NWN::NWObject getItemActivatedTarget(const Ice::Current&);
    virtual NWN::NWLocation getItemActivatedTargetLocation(const Ice::Current&);
    virtual NWN::NWObject getItemActivator(const Ice::Current&);
    virtual Ice::Int getItemAppearance(const NWN::NWObject& oItem, Ice::Int nType, Ice::Int nIndex, const Ice::Current&);
    virtual Ice::Int getItemCharges(const NWN::NWObject& oItem, const Ice::Current&);
    virtual bool getItemCursedFlag(const NWN::NWObject& oItem, const Ice::Current&);
    virtual bool getItemHasItemProperty(const NWN::NWObject& oItem, Ice::Int nProperty, const Ice::Current&);
    virtual NWN::NWObject getItemInSlot(NWN::InventorySlot tInventorySlot, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getItemPossessedBy(const NWN::NWObject& oCreature, const std::string& sItemTag, const Ice::Current&);
    virtual NWN::NWObject getItemPossessor(const NWN::NWObject& oItem, const Ice::Current&);
    virtual Ice::Int getItemPropertyCostTable(const NWN::NWItemProperty& iProp, const Ice::Current&);
    virtual Ice::Int getItemPropertyCostTableValue(const NWN::NWItemProperty& iProp, const Ice::Current&);
    virtual NWN::DurationType getItemPropertyDurationType(const NWN::NWItemProperty& ip, const Ice::Current&);
    virtual Ice::Int getItemPropertyParam1(const NWN::NWItemProperty& iProp, const Ice::Current&);
    virtual Ice::Int getItemPropertyParam1Value(const NWN::NWItemProperty& iProp, const Ice::Current&);
    virtual Ice::Int getItemPropertySubType(const NWN::NWItemProperty& iProperty, const Ice::Current&);
    virtual Ice::Int getItemPropertyType(const NWN::NWItemProperty& ip, const Ice::Current&);
    virtual Ice::Int getItemStackSize(const NWN::NWObject& oItem, const Ice::Current&);
    virtual Ice::Int getJournalQuestExperience(const std::string& szPlotID, const Ice::Current&);
    virtual std::string getKeyRequiredFeedback(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::AssociateCommand getLastAssociateCommand(const NWN::NWObject& oAssociate, const Ice::Current&);
    virtual NWN::CombatMode getLastAttackMode(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::SpecialAttack getLastAttackType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getLastAttacker(const NWN::NWObject& oAttackee, const Ice::Current&);
    virtual NWN::NWObject getLastClosedBy(const Ice::Current&);
    virtual NWN::NWObject getLastDamager(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::NWObject getLastDisarmed(const Ice::Current&);
    virtual NWN::NWObject getLastDisturbed(const Ice::Current&);
    virtual NWN::NWObject getLastHostileActor(const NWN::NWObject& oVictim, const Ice::Current&);
    virtual NWN::NWObject getLastKiller(const Ice::Current&);
    virtual NWN::NWObject getLastLocked(const Ice::Current&);
    virtual NWN::NWObject getLastOpenedBy(const Ice::Current&);
    virtual NWN::NWObject getLastPCRested(const Ice::Current&);
    virtual NWN::NWObject getLastPCToCancelCutscene(const Ice::Current&);
    virtual NWN::NWObject getLastPerceived(const Ice::Current&);
    virtual bool getLastPerceptionHeard(const Ice::Current&);
    virtual bool getLastPerceptionInaudible(const Ice::Current&);
    virtual bool getLastPerceptionSeen(const Ice::Current&);
    virtual bool getLastPerceptionVanished(const Ice::Current&);
    virtual NWN::NWObject getLastPlayerDied(const Ice::Current&);
    virtual NWN::NWObject getLastPlayerDying(const Ice::Current&);
    virtual NWN::NWObject getLastRespawnButtonPresser(const Ice::Current&);
    virtual Ice::Int getLastRestEventType(const Ice::Current&);
    virtual NWN::NWObject getLastSpeaker(const Ice::Current&);
    virtual Ice::Int getLastSpell(const Ice::Current&);
    virtual Ice::Int getLastSpellCastClass(const Ice::Current&);
    virtual NWN::NWObject getLastSpellCaster(const Ice::Current&);
    virtual bool getLastSpellHarmful(const Ice::Current&);
    virtual NWN::NWObject getLastTrapDetected(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWObject getLastUnlocked(const Ice::Current&);
    virtual NWN::NWObject getLastUsedBy(const Ice::Current&);
    virtual NWN::NWObject getLastWeaponUsed(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getLawChaosValue(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getLevelByClass(Ice::Int nClassType, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getLevelByPosition(Ice::Int nClassPosition, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getListenPatternNumber(const Ice::Current&);
    virtual Ice::Double getLocalFloat(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual Ice::Int getLocalInt(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual NWN::NWLocation getLocalLocation(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual NWN::NWObject getLocalObject(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual std::string getLocalString(const NWN::NWObject& oObject, const std::string& sVarName, const Ice::Current&);
    virtual NWN::NWLocation getLocation(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getLockKeyRequired(const NWN::NWObject& oObject, const Ice::Current&);
    virtual std::string getLockKeyTag(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Int getLockLockDC(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getLockLockable(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Int getLockUnlockDC(const NWN::NWObject& oObject, const Ice::Current&);
    virtual bool getLocked(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual bool getLootable(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getMaster(const NWN::NWObject& oAssociate, const Ice::Current&);
    virtual std::string getMatchedSubstring(Ice::Int nString, const Ice::Current&);
    virtual Ice::Int getMatchedSubstringsCount(const Ice::Current&);
    virtual Ice::Int getMaxHenchmen(const Ice::Current&);
    virtual Ice::Int getMaxHitPoints(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::MetaMagic getMetaMagicFeat(const Ice::Current&);
    virtual NWN::NWObject getModule(const Ice::Current&);
    virtual NWN::NWObject getModuleItemAcquired(const Ice::Current&);
    virtual NWN::NWObject getModuleItemAcquiredBy(const Ice::Current&);
    virtual NWN::NWObject getModuleItemAcquiredFrom(const Ice::Current&);
    virtual Ice::Int getModuleItemAcquiredStackSize(const Ice::Current&);
    virtual NWN::NWObject getModuleItemLost(const Ice::Current&);
    virtual NWN::NWObject getModuleItemLostBy(const Ice::Current&);
    virtual std::string getModuleName(const Ice::Current&);
    virtual Ice::Int getModuleXPScale(const Ice::Current&);
    virtual Ice::Int getMovementRate(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual std::string getName(const NWN::NWObject& oObject, bool bOriginalName, const Ice::Current&);
    virtual NWN::NWObject getNearestCreature(Ice::Int nFirstCriteriaType, Ice::Int nFirstCriteriaValue, const NWN::NWObject& oTarget, Ice::Int nNth, Ice::Int nSecondCriteriaType, Ice::Int nSecondCriteriaValue, Ice::Int nThirdCriteriaType, Ice::Int nThirdCriteriaValue, const Ice::Current&);
    virtual NWN::NWObject getNearestCreatureToLocation(Ice::Int nFirstCriteriaType, Ice::Int nFirstCriteriaValue, const NWN::NWLocation& lLocation, Ice::Int nNth, Ice::Int nSecondCriteriaType, Ice::Int nSecondCriteriaValue, Ice::Int nThirdCriteriaType, Ice::Int nThirdCriteriaValue, const Ice::Current&);
    virtual NWN::NWObject getNearestObject(NWN::ObjectType tObjectType, const NWN::NWObject& oTarget, Ice::Int nNth, const Ice::Current&);
    virtual NWN::NWObject getNearestObjectByTag(const std::string& sTag, const NWN::NWObject& oTarget, Ice::Int nNth, const Ice::Current&);
    virtual NWN::NWObject getNearestObjectToLocation(NWN::ObjectType tObjectType, const NWN::NWLocation& lLocation, Ice::Int nNth, const Ice::Current&);
    virtual NWN::NWObject getNearestTrapToObject(const NWN::NWObject& oTarget, bool bTrapDetected, const Ice::Current&);
    virtual NWN::NWEffect getNextEffect(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWObject getNextFactionMember(const NWN::NWObject& oMemberOfFaction, bool bPCOnly, const Ice::Current&);
    virtual NWN::NWObject getNextInPersistentObject(const NWN::NWObject& oPersistentObject, Ice::Int nResidentObjectType, Ice::Int nPersistentZone, const Ice::Current&);
    virtual NWN::NWObject getNextItemInInventory(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWItemProperty getNextItemProperty(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getNextObjectInArea(const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::NWObject getNextObjectInShape(NWN::ShapeType tShapeType, Ice::Double fSize, const NWN::NWLocation& lTarget, bool bLineOfSight, Ice::Int nObjectFilter, const NWN::NWVector& vOrigin, const Ice::Current&);
    virtual NWN::NWObject getNextPC(const Ice::Current&);
    virtual Ice::Int getNumStackedItems(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::NWObject getObjectByTag(const std::string& sTag, Ice::Int nNth, const Ice::Current&);
    virtual bool getObjectHeard(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual bool getObjectSeen(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, const Ice::Current&);
    virtual NWN::ObjectType getObjectType(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual std::string getPCChatMessage(const Ice::Current&);
    virtual NWN::NWObject getPCChatSpeaker(const Ice::Current&);
    virtual Ice::Int getPCChatVolume(const Ice::Current&);
    virtual std::string getPCIPAddress(const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual NWN::NWObject getPCItemLastEquipped(const Ice::Current&);
    virtual NWN::NWObject getPCItemLastEquippedBy(const Ice::Current&);
    virtual NWN::NWObject getPCItemLastUnequipped(const Ice::Current&);
    virtual NWN::NWObject getPCItemLastUnequippedBy(const Ice::Current&);
    virtual NWN::NWObject getPCLevellingUp(const Ice::Current&);
    virtual std::string getPCPlayerName(const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual std::string getPCPublicCDKey(const NWN::NWObject& oPlayer, bool bSinglePlayerCDKey, const Ice::Current&);
    virtual NWN::NWObject getPCSpeaker(const Ice::Current&);
    virtual NWN::PhenoType getPhenoType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getPickpocketableFlag(const NWN::NWObject& oItem, const Ice::Current&);
    virtual Ice::Int getPlaceableIllumination(const NWN::NWObject& oPlaceable, const Ice::Current&);
    virtual NWN::NWObject getPlaceableLastClickedBy(const Ice::Current&);
    virtual bool getPlotFlag(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getPortraitId(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual std::string getPortraitResRef(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWVector getPosition(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual NWN::NWVector getPositionFromLocation(const NWN::NWLocation& lLocation, const Ice::Current&);
    virtual NWN::RacialType getRacialType(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getReflexAdjustedDamage(Ice::Int nDamage, const NWN::NWObject& oTarget, Ice::Int nDC, NWN::SaveType tSaveType, const NWN::NWObject& oSaveVersus, const Ice::Current&);
    virtual Ice::Int getReflexSavingThrow(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getReputation(const NWN::NWObject& oSource, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual std::string getResRef(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::NWObject getSittingCreature(const NWN::NWObject& oChair, const Ice::Current&);
    virtual Ice::Int getSkillRank(Ice::Int nSkill, const NWN::NWObject& oTarget, bool bBaseSkillRank, const Ice::Current&);
    virtual Ice::Int getSkyBox(const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::NWObject getSpellCastItem(const Ice::Current&);
    virtual Ice::Int getSpellId(const Ice::Current&);
    virtual Ice::Int getSpellResistance(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getSpellSaveDC(const Ice::Current&);
    virtual NWN::NWLocation getSpellTargetLocation(const Ice::Current&);
    virtual NWN::NWObject getSpellTargetObject(const Ice::Current&);
    virtual Ice::Int getStandardFactionReputation(NWN::StandardFaction tStandardFaction, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWLocation getStartingLocation(const Ice::Current&);
    virtual Ice::Int getStealthMode(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual bool getStolenFlag(const NWN::NWObject& oStolen, const Ice::Current&);
    virtual Ice::Int getStoreGold(const NWN::NWObject& oidStore, const Ice::Current&);
    virtual Ice::Int getStoreIdentifyCost(const NWN::NWObject& oidStore, const Ice::Current&);
    virtual Ice::Int getStoreMaxBuyPrice(const NWN::NWObject& oidStore, const Ice::Current&);
    virtual Ice::Double getStrRefSoundDuration(Ice::Int nStrRef, const Ice::Current&);
    virtual std::string getStringByStrRef(Ice::Int nStrRef, NWN::Gender tGender, const Ice::Current&);
    virtual std::string getStringLeft(const std::string& sString, Ice::Int nCount, const Ice::Current&);
    virtual Ice::Int getStringLength(const std::string& sString, const Ice::Current&);
    virtual std::string getStringLowerCase(const std::string& sString, const Ice::Current&);
    virtual std::string getStringRight(const std::string& sString, Ice::Int nCount, const Ice::Current&);
    virtual std::string getStringUpperCase(const std::string& sString, const Ice::Current&);
    virtual std::string getSubRace(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual std::string getSubString(const std::string& sString, Ice::Int nStart, Ice::Int nCount, const Ice::Current&);
    virtual std::string getTag(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::TileMainLightColor getTileMainLight1Color(const NWN::NWLocation& lTile, const Ice::Current&);
    virtual NWN::TileMainLightColor getTileMainLight2Color(const NWN::NWLocation& lTile, const Ice::Current&);
    virtual NWN::TileSourceLightColor getTileSourceLight1Color(const NWN::NWLocation& lTile, const Ice::Current&);
    virtual NWN::TileSourceLightColor getTileSourceLight2Color(const NWN::NWLocation& lTile, const Ice::Current&);
    virtual std::string getTilesetResRef(const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int getTimeHour(const Ice::Current&);
    virtual Ice::Int getTimeMillisecond(const Ice::Current&);
    virtual Ice::Int getTimeMinute(const Ice::Current&);
    virtual Ice::Int getTimeSecond(const Ice::Current&);
    virtual Ice::Int getTotalDamageDealt(const Ice::Current&);
    virtual NWN::NWObject getTransitionTarget(const NWN::NWObject& oTransition, const Ice::Current&);
    virtual bool getTrapActive(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual Ice::Int getTrapBaseType(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual NWN::NWObject getTrapCreator(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual Ice::Int getTrapDetectDC(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapDetectable(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapDetectedBy(const NWN::NWObject& oTrapObject, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual Ice::Int getTrapDisarmDC(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapDisarmable(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapFlagged(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual std::string getTrapKeyTag(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapOneShot(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual bool getTrapRecoverable(const NWN::NWObject& oTrapObject, const Ice::Current&);
    virtual Ice::Int getTurnResistanceHD(const NWN::NWObject& oUndead, const Ice::Current&);
    virtual bool getUseableFlag(const NWN::NWObject& oObject, const Ice::Current&);
    virtual Ice::Int getUserDefinedEventNumber(const Ice::Current&);
    virtual NWN::NWObject getWaypointByTag(const std::string& sWaypointTag, const Ice::Current&);
    virtual bool getWeaponRanged(const NWN::NWObject& oItem, const Ice::Current&);
    virtual NWN::Weather getWeather(const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int getWeight(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getWillSavingThrow(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int getXP(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void giveGoldToCreature(const NWN::NWObject& oCreature, Ice::Int nGP, const Ice::Current&);
    virtual void giveXPToCreature(const NWN::NWObject& oCreature, Ice::Int nXpAmount, const Ice::Current&);
    virtual Ice::Double hoursToSeconds(Ice::Int nHours, const Ice::Current&);
    virtual void incrementRemainingFeatUses(const NWN::NWObject& oCreature, Ice::Int nFeat, const Ice::Current&);
    virtual std::string insertString(const std::string& sDestination, const std::string& sString, Ice::Int nPosition, const Ice::Current&);
    virtual Ice::Double intToFloat(Ice::Int nInteger, const Ice::Current&);
    virtual std::string intToHexString(Ice::Int nInteger, const Ice::Current&);
    virtual std::string intToString(Ice::Int nInteger, const Ice::Current&);
    virtual bool isInConversation(const NWN::NWObject& oObject, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyACBonus(Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyACBonusVsAlign(Ice::Int nAlignGroup, Ice::Int nACBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyACBonusVsDmgType(Ice::Int nDamageType, Ice::Int nACBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyACBonusVsRace(NWN::IPRacialType tIPRacialType, Ice::Int nACBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyACBonusVsSAlign(Ice::Int nAlign, Ice::Int nACBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAbilityBonus(NWN::Ability tAbility, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAdditional(Ice::Int nAdditionalProperty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyArcaneSpellFailure(Ice::Int nModLevel, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAttackBonus(Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAttackBonusVsAlign(Ice::Int nAlignGroup, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAttackBonusVsRace(NWN::IPRacialType tIPRacialType, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAttackBonusVsSAlign(Ice::Int nAlignment, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyAttackPenalty(Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyBonusFeat(Ice::Int nFeat, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyBonusLevelSpell(Ice::Int nClass, Ice::Int nSpellLevel, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyBonusSavingThrow(Ice::Int nBaseSaveType, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyBonusSavingThrowVsX(Ice::Int nBonusType, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyBonusSpellResistance(Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyCastSpell(Ice::Int nSpell, Ice::Int nNumUses, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyContainerReducedWeight(Ice::Int nContainerType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageBonus(Ice::Int nDamageType, Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageBonusVsAlign(Ice::Int nAlignGroup, Ice::Int nDamageType, Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageBonusVsRace(NWN::IPRacialType tIPRacialType, Ice::Int nDamageType, Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageBonusVsSAlign(Ice::Int nAlign, Ice::Int nDamageType, Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageImmunity(Ice::Int nDamageType, Ice::Int nImmuneBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamagePenalty(Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageReduction(Ice::Int nEnhancement, Ice::Int nHPSoak, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageResistance(Ice::Int nDamageType, Ice::Int nHPResist, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDamageVulnerability(Ice::Int nDamageType, Ice::Int nVulnerability, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDarkvision(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDecreaseAC(Ice::Int nModifierType, Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDecreaseAbility(NWN::Ability tAbility, Ice::Int nModifier, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyDecreaseSkill(Ice::Int nSkill, Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyEnhancementBonus(Ice::Int nEnhancementBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyEnhancementBonusVsAlign(Ice::Int nAlignGroup, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyEnhancementBonusVsRace(NWN::IPRacialType tIPRacialType, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyEnhancementBonusVsSAlign(Ice::Int nAlign, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyEnhancementPenalty(Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyExtraMeleeDamageType(Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyExtraRangeDamageType(Ice::Int nDamageType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyFreeAction(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyHaste(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyHealersKit(Ice::Int nModifier, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyHolyAvenger(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyImmunityMisc(Ice::Int nImmunityType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyImmunityToSpellLevel(Ice::Int nLevel, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyImprovedEvasion(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyKeen(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyLight(Ice::Int nBrightness, Ice::Int nColor, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyLimitUseByAlign(Ice::Int nAlignGroup, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyLimitUseByClass(Ice::Int nClass, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyLimitUseByRace(NWN::IPRacialType tIPRacialType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyLimitUseBySAlign(Ice::Int nAlignment, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyMassiveCritical(Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyMaterial(Ice::Int nMaterialType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyMaxRangeStrengthMod(Ice::Int nModifier, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyMonsterDamage(Ice::Int nDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyNoDamage(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyOnHitCastSpell(Ice::Int nSpell, Ice::Int nLevel, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyOnHitProps(Ice::Int nProperty, Ice::Int nSaveDC, Ice::Int nSpecial, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyOnMonsterHitProperties(Ice::Int nProperty, Ice::Int nSpecial, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyQuality(Ice::Int nQuality, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyReducedSavingThrow(Ice::Int nBonusType, Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyReducedSavingThrowVsX(Ice::Int nBaseSaveType, Ice::Int nPenalty, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyRegeneration(Ice::Int nRegenAmount, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertySkillBonus(Ice::Int nSkill, Ice::Int nBonus, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertySpecialWalk(Ice::Int nWalkType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertySpellImmunitySchool(Ice::Int nSchool, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertySpellImmunitySpecific(Ice::Int nSpell, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyThievesTools(Ice::Int nModifier, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyTrap(Ice::Int nTrapLevel, Ice::Int nTrapType, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyTrueSeeing(const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyTurnResistance(Ice::Int nModifier, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyUnlimitedAmmo(Ice::Int nAmmoDamage, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyVampiricRegeneration(Ice::Int nRegenAmount, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyVisualEffect(Ice::Int nEffect, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyWeightIncrease(Ice::Int nWeight, const Ice::Current&);
    virtual NWN::NWItemProperty itemPropertyWeightReduction(Ice::Int nReduction, const Ice::Current&);
    virtual void jumpToLocation(const NWN::NWLocation& lDestination, const Ice::Current&);
    virtual void jumpToObject(const NWN::NWObject& oToJumpTo, bool bWalkStraightLineToPoint, const Ice::Current&);
    virtual Ice::Int levelUpHenchman(const NWN::NWObject& oCreature, Ice::Int nClass, bool bReadyAllSpells, Ice::Int nPackage, const Ice::Current&);
    virtual Ice::Int lineOfSightObject(const NWN::NWObject& oSource, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual Ice::Int lineOfSightVector(const NWN::NWVector& vSource, const NWN::NWVector& vTarget, const Ice::Current&);
    virtual NWN::NWLocation location(const NWN::NWObject& oArea, const NWN::NWVector& vPosition, Ice::Double fOrientation, const Ice::Current&);
    virtual void lockCameraDirection(const NWN::NWObject& oPlayer, bool bLocked, const Ice::Current&);
    virtual void lockCameraDistance(const NWN::NWObject& oPlayer, bool bLocked, const Ice::Current&);
    virtual void lockCameraPitch(const NWN::NWObject& oPlayer, bool bLocked, const Ice::Current&);
    virtual Ice::Double log(Ice::Double fValue, const Ice::Current&);
    virtual NWN::NWEffect magicalEffect(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual void musicBackgroundChangeDay(const NWN::NWObject& oArea, Ice::Int nTrack, const Ice::Current&);
    virtual void musicBackgroundChangeNight(const NWN::NWObject& oArea, Ice::Int nTrack, const Ice::Current&);
    virtual Ice::Int musicBackgroundGetBattleTrack(const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int musicBackgroundGetDayTrack(const NWN::NWObject& oArea, const Ice::Current&);
    virtual Ice::Int musicBackgroundGetNightTrack(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void musicBackgroundPlay(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void musicBackgroundSetDelay(const NWN::NWObject& oArea, Ice::Int nDelay, const Ice::Current&);
    virtual void musicBackgroundStop(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void musicBattleChange(const NWN::NWObject& oArea, Ice::Int nTrack, const Ice::Current&);
    virtual void musicBattlePlay(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void musicBattleStop(const NWN::NWObject& oArea, const Ice::Current&);
    virtual void nightToDay(const NWN::NWObject& oPlayer, Ice::Double fTransitionTime, const Ice::Current&);
    virtual std::string objectToString(const NWN::NWObject& oObject, const Ice::Current&);
    virtual void openInventory(const NWN::NWObject& oCreature, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void openStore(const NWN::NWObject& oStore, const NWN::NWObject& oPC, Ice::Int nBonusMarkUp, Ice::Int nBonusMarkDown, const Ice::Current&);
    virtual void playAnimation(Ice::Int nAnimation, Ice::Double fSpeed, Ice::Double fSeconds, const Ice::Current&);
    virtual void playSound(const std::string& sSoundName, const Ice::Current&);
    virtual void playSoundByStrRef(Ice::Int nStrRef, Ice::Int nRunAsAction, const Ice::Current&);
    virtual void playVoiceChat(Ice::Int nVoiceChatID, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void popUpDeathGUIPanel(const NWN::NWObject& oPC, bool bRespawnButtonEnabled, bool bWaitForHelpButtonEnabled, Ice::Int nHelpStringReference, const std::string& sHelpString, const Ice::Current&);
    virtual void popUpGUIPanel(const NWN::NWObject& oPC, Ice::Int nGUIPanel, const Ice::Current&);
    virtual Ice::Double pow(Ice::Double fValue, Ice::Double fExponent, const Ice::Current&);
    virtual void printFloat(Ice::Double fFloat, Ice::Int nWidth, Ice::Int nDecimals, const Ice::Current&);
    virtual void printInteger(Ice::Int nInteger, const Ice::Current&);
    virtual void printObject(const NWN::NWObject& oObject, const Ice::Current&);
    virtual void printString(const std::string& sString, const Ice::Current&);
    virtual void printVector(const NWN::NWVector& vVector, bool bPrepend, const Ice::Current&);
    virtual Ice::Int random(Ice::Int nMaxInteger, const Ice::Current&);
    virtual std::string randomName(Ice::Int nNameType, const Ice::Current&);
    virtual void recomputeStaticLighting(const NWN::NWObject& oArea, const Ice::Current&);
    virtual NWN::SavingThrowResult reflexSave(const NWN::NWObject& oCreature, Ice::Int nDC, NWN::SaveType tSaveType, const NWN::NWObject& oSaveVersus, const Ice::Current&);
    virtual void removeEffect(const NWN::NWObject& oCreature, const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual void removeFromParty(const NWN::NWObject& oPC, const Ice::Current&);
    virtual void removeHenchman(const NWN::NWObject& oMaster, const NWN::NWObject& oHenchman, const Ice::Current&);
    virtual void removeItemProperty(const NWN::NWObject& oItem, const NWN::NWItemProperty& ipProperty, const Ice::Current&);
    virtual void removeJournalQuestEntry(const std::string& szPlotID, const NWN::NWObject& oCreature, bool bAllPartyMembers, bool bAllPlayers, const Ice::Current&);
    virtual void removeSummonedAssociate(const NWN::NWObject& oMaster, const NWN::NWObject& oAssociate, const Ice::Current&);
    virtual Ice::Int resistSpell(const NWN::NWObject& oCaster, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void restoreBaseAttackBonus(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void restoreCameraFacing(const Ice::Current&);
    virtual NWN::NWObject retrieveCampaignObject(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWLocation& locLocation, const NWN::NWObject& oOwner, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual Ice::Double roundsToSeconds(Ice::Int nRounds, const Ice::Current&);
    virtual void sendMessageToAllDMs(const std::string& szMessage, const Ice::Current&);
    virtual void sendMessageToPC(const NWN::NWObject& oPlayer, const std::string& szMessage, const Ice::Current&);
    virtual void sendMessageToPCByStrRef(const NWN::NWObject& oPlayer, Ice::Int nStrRef, const Ice::Current&);
    virtual void setAILevel(const NWN::NWObject& oTarget, Ice::Int nAILevel, const Ice::Current&);
    virtual void setActionMode(const NWN::NWObject& oCreature, Ice::Int nMode, Ice::Int nStatus, const Ice::Current&);
    virtual void setAreaTransitionBMP(Ice::Int nPredefinedAreaTransition, const std::string& sCustomAreaTransitionBMP, const Ice::Current&);
    virtual void setAssociateListenPatterns(const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void setBaseAttackBonus(Ice::Int nBaseAttackBonus, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setCalendar(Ice::Int nYear, Ice::Int nMonth, Ice::Int nDay, const Ice::Current&);
    virtual void setCameraFacing(Ice::Double fDirection, Ice::Double fDistance, Ice::Double fPitch, Ice::Int nTransitionType, const Ice::Current&);
    virtual void setCameraHeight(const NWN::NWObject& oPlayer, Ice::Double fHeight, const Ice::Current&);
    virtual void setCameraMode(const NWN::NWObject& oPlayer, Ice::Int nCameraMode, const Ice::Current&);
    virtual void setCampaignFloat(const std::string& sCampaignName, const std::string& sVarName, Ice::Double flFloat, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void setCampaignInt(const std::string& sCampaignName, const std::string& sVarName, Ice::Int nInt, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void setCampaignLocation(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWLocation& locLocation, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void setCampaignString(const std::string& sCampaignName, const std::string& sVarName, const std::string& sString, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void setCampaignVector(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWVector& vVector, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual void setColor(const NWN::NWObject& oObject, Ice::Int nColorChannel, Ice::Int nColorValue, const Ice::Current&);
    virtual void setCommandable(bool bCommandable, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void setCreatureAppearanceType(const NWN::NWObject& oCreature, Ice::Int nAppearanceType, const Ice::Current&);
    virtual void setCreatureBodyPart(Ice::Int nPart, Ice::Int nModelNumber, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setCreatureTailType(Ice::Int nTailType, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setCreatureWingType(Ice::Int nWingType, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setCustomToken(Ice::Int nCustomTokenNumber, const std::string& sTokenValue, const Ice::Current&);
    virtual void setCutsceneCameraMoveRate(const NWN::NWObject& oCreature, Ice::Double fRate, const Ice::Current&);
    virtual void setCutsceneMode(const NWN::NWObject& oCreature, bool bInCutscene, bool bLeftClickingEnabled, const Ice::Current&);
    virtual void setDeity(const NWN::NWObject& oCreature, const std::string& sDeity, const Ice::Current&);
    virtual void setDescription(const NWN::NWObject& oObject, const std::string& sNewDescription, bool bIdentifiedDescription, const Ice::Current&);
    virtual void setDroppableFlag(const NWN::NWObject& oItem, bool bDroppable, const Ice::Current&);
    virtual void setEncounterActive(bool bNewValue, const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual void setEncounterDifficulty(Ice::Int nEncounterDifficulty, const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual void setEncounterSpawnsCurrent(Ice::Int nNewValue, const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual void setEncounterSpawnsMax(Ice::Int nNewValue, const NWN::NWObject& oEncounter, const Ice::Current&);
    virtual void setFacing(Ice::Double fDirection, const Ice::Current&);
    virtual void setFacingPoint(const NWN::NWVector& vTarget, const Ice::Current&);
    virtual void setFogAmount(Ice::Int nFogType, Ice::Int nFogAmount, const NWN::NWObject& oArea, const Ice::Current&);
    virtual void setFogColor(Ice::Int nFogType, Ice::Int nFogColor, const NWN::NWObject& oArea, const Ice::Current&);
    virtual void setFootstepType(Ice::Int nFootstepType, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setFortitudeSavingThrow(const NWN::NWObject& oObject, Ice::Int nFortitudeSave, const Ice::Current&);
    virtual void setHardness(Ice::Int nHardness, const NWN::NWObject& oObject, const Ice::Current&);
    virtual void setIdentified(const NWN::NWObject& oItem, bool bIdentified, const Ice::Current&);
    virtual void setImmortal(const NWN::NWObject& oCreature, bool bImmortal, const Ice::Current&);
    virtual void setInfiniteFlag(const NWN::NWObject& oItem, bool bInfinite, const Ice::Current&);
    virtual void setIsDestroyable(bool bDestroyable, bool bRaiseable, bool bSelectableWhenDead, const Ice::Current&);
    virtual void setIsTemporaryEnemy(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, bool bDecays, Ice::Double fDurationInSeconds, const Ice::Current&);
    virtual void setIsTemporaryFriend(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, bool bDecays, Ice::Double fDurationInSeconds, const Ice::Current&);
    virtual void setIsTemporaryNeutral(const NWN::NWObject& oTarget, const NWN::NWObject& oSource, bool bDecays, Ice::Double fDurationInSeconds, const Ice::Current&);
    virtual void setItemCharges(const NWN::NWObject& oItem, Ice::Int nCharges, const Ice::Current&);
    virtual void setItemCursedFlag(const NWN::NWObject& oItem, bool bCursed, const Ice::Current&);
    virtual void setItemStackSize(const NWN::NWObject& oItem, Ice::Int nSize, const Ice::Current&);
    virtual void setKeyRequiredFeedback(const NWN::NWObject& oObject, const std::string& sFeedbackMessage, const Ice::Current&);
    virtual void setListenPattern(const NWN::NWObject& oObject, const std::string& sPattern, Ice::Int nNumber, const Ice::Current&);
    virtual void setListening(const NWN::NWObject& oObject, bool bValue, const Ice::Current&);
    virtual void setLocalFloat(const NWN::NWObject& oObject, const std::string& sVarName, Ice::Double fValue, const Ice::Current&);
    virtual void setLocalInt(const NWN::NWObject& oObject, const std::string& sVarName, Ice::Int nValue, const Ice::Current&);
    virtual void setLocalLocation(const NWN::NWObject& oObject, const std::string& sVarName, const NWN::NWLocation& lValue, const Ice::Current&);
    virtual void setLocalObject(const NWN::NWObject& oObject, const std::string& sVarName, const NWN::NWObject& oValue, const Ice::Current&);
    virtual void setLocalString(const NWN::NWObject& oObject, const std::string& sVarName, const std::string& sValue, const Ice::Current&);
    virtual void setLockKeyRequired(const NWN::NWObject& oObject, bool bKeyRequired, const Ice::Current&);
    virtual void setLockKeyTag(const NWN::NWObject& oObject, const std::string& sNewKeyTag, const Ice::Current&);
    virtual void setLockLockDC(const NWN::NWObject& oObject, Ice::Int nNewLockDC, const Ice::Current&);
    virtual void setLockLockable(const NWN::NWObject& oObject, bool bLockable, const Ice::Current&);
    virtual void setLockUnlockDC(const NWN::NWObject& oObject, Ice::Int nNewUnlockDC, const Ice::Current&);
    virtual void setLocked(const NWN::NWObject& oTarget, bool bLocked, const Ice::Current&);
    virtual void setLootable(const NWN::NWObject& oCreature, bool bLootable, const Ice::Current&);
    virtual void setMapPinEnabled(const NWN::NWObject& oMapPin, bool bEnabled, const Ice::Current&);
    virtual void setMaxHenchmen(Ice::Int nNumHenchmen, const Ice::Current&);
    virtual void setModuleXPScale(Ice::Int nXPScale, const Ice::Current&);
    virtual void setName(const NWN::NWObject& oObject, const std::string& sNewName, const Ice::Current&);
    virtual void setPCChatMessage(const std::string& sNewChatMessage, const Ice::Current&);
    virtual void setPCChatVolume(NWN::TalkVolume tTalkVolume, const Ice::Current&);
    virtual void setPCDislike(const NWN::NWObject& oPlayer, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void setPCLike(const NWN::NWObject& oPlayer, const NWN::NWObject& oTarget, const Ice::Current&);
    virtual void setPanelButtonFlash(const NWN::NWObject& oPlayer, NWN::Button tButton, bool bEnableFlash, const Ice::Current&);
    virtual void setPhenoType(NWN::PhenoType tPhenoType, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setPickpocketableFlag(const NWN::NWObject& oItem, bool bPickpocketable, const Ice::Current&);
    virtual void setPlaceableIllumination(const NWN::NWObject& oPlaceable, bool bIlluminate, const Ice::Current&);
    virtual void setPlotFlag(const NWN::NWObject& oTarget, bool bPlotFlag, const Ice::Current&);
    virtual void setPortraitId(const NWN::NWObject& oTarget, Ice::Int nPortraitId, const Ice::Current&);
    virtual void setPortraitResRef(const NWN::NWObject& oTarget, const std::string& sPortraitResRef, const Ice::Current&);
    virtual void setReflexSavingThrow(const NWN::NWObject& oObject, Ice::Int nReflexSave, const Ice::Current&);
    virtual void setSkyBox(Ice::Int nSkyBox, const NWN::NWObject& oArea, const Ice::Current&);
    virtual void setStandardFactionReputation(NWN::StandardFaction tStandardFaction, Ice::Int nNewReputation, const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void setStolenFlag(const NWN::NWObject& oItem, bool bStolenFlag, const Ice::Current&);
    virtual void setStoreGold(const NWN::NWObject& oidStore, Ice::Int nGold, const Ice::Current&);
    virtual void setStoreIdentifyCost(const NWN::NWObject& oidStore, Ice::Int nCost, const Ice::Current&);
    virtual void setStoreMaxBuyPrice(const NWN::NWObject& oidStore, Ice::Int nMaxBuy, const Ice::Current&);
    virtual void setSubRace(const NWN::NWObject& oCreature, const std::string& sSubRace, const Ice::Current&);
    virtual void setTileMainLightColor(const NWN::NWLocation& lTileLocation, NWN::TileMainLightColor nMainLight1Color, NWN::TileMainLightColor nMainLight2Color, const Ice::Current&);
    virtual void setTileSourceLightColor(const NWN::NWLocation& lTileLocation, NWN::TileSourceLightColor nSourceLight1Color, NWN::TileSourceLightColor nSourceLight2Color, const Ice::Current&);
    virtual void setTime(Ice::Int nHour, Ice::Int nMinute, Ice::Int nSecond, Ice::Int nMillisecond, const Ice::Current&);
    virtual void setTrapActive(const NWN::NWObject& oTrapObject, bool bActive, const Ice::Current&);
    virtual void setTrapDetectDC(const NWN::NWObject& oTrapObject, Ice::Int nDetectDC, const Ice::Current&);
    virtual void setTrapDetectable(const NWN::NWObject& oTrapObject, bool bDetectable, const Ice::Current&);
    virtual Ice::Int setTrapDetectedBy(const NWN::NWObject& oTrap, const NWN::NWObject& oDetector, bool bDetected, const Ice::Current&);
    virtual void setTrapDisabled(const NWN::NWObject& oTrap, const Ice::Current&);
    virtual void setTrapDisarmDC(const NWN::NWObject& oTrapObject, Ice::Int nDisarmDC, const Ice::Current&);
    virtual void setTrapDisarmable(const NWN::NWObject& oTrapObject, bool bDisarmable, const Ice::Current&);
    virtual void setTrapKeyTag(const NWN::NWObject& oTrapObject, const std::string& sKeyTag, const Ice::Current&);
    virtual void setTrapOneShot(const NWN::NWObject& oTrapObject, bool bOneShot, const Ice::Current&);
    virtual void setTrapRecoverable(const NWN::NWObject& oTrapObject, bool bRecoverable, const Ice::Current&);
    virtual void setUseableFlag(const NWN::NWObject& oPlaceable, bool bUseableFlag, const Ice::Current&);
    virtual void setWeather(const NWN::NWObject& oTarget, NWN::Weather tWeather, const Ice::Current&);
    virtual void setWillSavingThrow(const NWN::NWObject& oObject, Ice::Int nWillSave, const Ice::Current&);
    virtual void setXP(const NWN::NWObject& oCreature, Ice::Int nXpAmount, const Ice::Current&);
    virtual Ice::Double sin(Ice::Double fValue, const Ice::Current&);
    virtual void soundObjectPlay(const NWN::NWObject& oSound, const Ice::Current&);
    virtual void soundObjectSetPosition(const NWN::NWObject& oSound, const NWN::NWVector& vPosition, const Ice::Current&);
    virtual void soundObjectSetVolume(const NWN::NWObject& oSound, Ice::Int nVolume, const Ice::Current&);
    virtual void soundObjectStop(const NWN::NWObject& oSound, const Ice::Current&);
    virtual void spawnScriptDebugger(const Ice::Current&);
    virtual void speakOneLinerConversation(const std::string& sDialogResRef, const NWN::NWObject& oTokenTarget, const Ice::Current&);
    virtual void speakString(const std::string& sStringToSpeak, NWN::TalkVolume tTalkVolume, const Ice::Current&);
    virtual void speakStringByStrRef(Ice::Int nStrRef, NWN::TalkVolume tTalkVolume, const Ice::Current&);
    virtual Ice::Double sqrt(Ice::Double fValue, const Ice::Current&);
    virtual void startNewModule(const std::string& sModuleName, const Ice::Current&);
    virtual void stopFade(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual void storeCameraFacing(const Ice::Current&);
    virtual Ice::Int storeCampaignObject(const std::string& sCampaignName, const std::string& sVarName, const NWN::NWObject& oObject, const NWN::NWObject& oPlayer, const Ice::Current&);
    virtual Ice::Double stringToFloat(const std::string& sNumber, const Ice::Current&);
    virtual Ice::Int stringToInt(const std::string& sNumber, const Ice::Current&);
    virtual void summonAnimalCompanion(const NWN::NWObject& oMaster, const Ice::Current&);
    virtual void summonFamiliar(const NWN::NWObject& oMaster, const Ice::Current&);
    virtual NWN::NWEffect supernaturalEffect(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual void surrenderToEnemies(const Ice::Current&);
    virtual void takeGoldFromCreature(Ice::Int nAmount, const NWN::NWObject& oCreatureToTakeFrom, bool bDestroy, const Ice::Current&);
    virtual Ice::Double tan(Ice::Double fValue, const Ice::Current&);
    virtual Ice::Int testStringAgainstPattern(const std::string& sPattern, const std::string& sStringToTest, const Ice::Current&);
    virtual NWN::AttackResult touchAttackMelee(const NWN::NWObject& oTarget, bool bDisplayFeedback, const Ice::Current&);
    virtual NWN::AttackResult touchAttackRanged(const NWN::NWObject& oTarget, bool bDisplayFeedback, const Ice::Current&);
    virtual Ice::Double turnsToSeconds(Ice::Int nTurns, const Ice::Current&);
    virtual void unpossessFamiliar(const NWN::NWObject& oCreature, const Ice::Current&);
    virtual NWN::NWVector vector(Ice::Double x, Ice::Double y, Ice::Double z, const Ice::Current&);
    virtual Ice::Double vectorMagnitude(const NWN::NWVector& vVector, const Ice::Current&);
    virtual NWN::NWVector vectorNormalize(const NWN::NWVector& vVector, const Ice::Current&);
    virtual Ice::Double vectorToAngle(const NWN::NWVector& vVector, const Ice::Current&);
    virtual NWN::NWEffect versusAlignmentEffect(const NWN::NWEffect& eEffect, Ice::Int nLawChaos, Ice::Int nGoodEvil, const Ice::Current&);
    virtual NWN::NWEffect versusRacialTypeEffect(const NWN::NWEffect& eEffect, NWN::RacialType tRacialType, const Ice::Current&);
    virtual NWN::NWEffect versusTrapEffect(const NWN::NWEffect& eEffect, const Ice::Current&);
    virtual NWN::SavingThrowResult willSave(const NWN::NWObject& oCreature, Ice::Int nDC, NWN::SaveType tSaveType, const NWN::NWObject& oSaveVersus, const Ice::Current&);
    virtual void writeTimestampedLogEntry(const std::string& sLogEntry, const Ice::Current&);
    virtual Ice::Double yardsToMeters(Ice::Double fYards, const Ice::Current&);
  private:
    IceUtil::Mutex mutex;
    void innerLock(const char*);
    void innerUnlock(const char*);
    std::map<std::string, NWN::Persistable> persistMap;
    std::map<long,CGameEffect*> effectMap;
    std::map<long,CGameEffect*> iprpMap;
    long lastEffectId, lastIprpId;
};
